using System.Collections.Generic;
using Newtonsoft.Json;
using NUnit.Framework;

public class NineLivesModelTests
{
    NineLivesModel Introduced() { var m = new NineLivesModel(); m.CompleteLevel("intro", "intro", 3); return m; }
    [Test] public void IntroGrantsFreePointWithoutXpAndOnlyOnce() { var m = Introduced(); Assert.That(m.UnspentPoints, Is.EqualTo(1)); Assert.That(m.TotalXp, Is.Zero); Assert.That(m.NextPointCost, Is.EqualTo(150)); Assert.That(m.CompleteLevel("intro", "intro", 3), Is.False); Assert.That(m.TotalXp, Is.EqualTo(30)); }
    [Test] public void DamageAndFirstClearOneStarGive115() { var m = Introduced(); m.AddXp(20); m.CompleteLevel("two", "intro", 1); Assert.That(m.TotalXp, Is.EqualTo(115)); m.CompleteLevel("two", "intro", 3); Assert.That(m.TotalXp, Is.EqualTo(155)); }
    [Test] public void OverflowEarnsMultiplePointsAndCapsCurrency() { var m = Introduced(); m.AddXp(150 + 240 + 10); Assert.That(m.LifetimePoints, Is.EqualTo(3)); Assert.That(m.XpTowardNextPoint, Is.EqualTo(10)); Assert.That(m.NextPointCost, Is.EqualTo(330)); m.AddXp(int.MaxValue); Assert.That(m.LifetimePoints, Is.EqualTo(15)); Assert.That(m.TotalXp, Is.EqualTo(10290)); Assert.That(m.NextPointCost, Is.Zero); Assert.That(m.XpTowardNextPoint, Is.Zero); }
    [Test] public void CapstoneNeedsEightLifetimePointsAndRespecPreservesEarnings() { var m = Introduced(); m.AddXp(1140); foreach (var id in new[] { "A1", "A2", "A3", "A4" }) Assert.That(m.Purchase(id), Is.True); Assert.That(m.Purchase("A5"), Is.False); m.AddXp(1800); Assert.That(m.LifetimePoints, Is.EqualTo(8)); Assert.That(m.Purchase("A5"), Is.True); m.Respec(); Assert.That(m.UnspentPoints, Is.EqualTo(8)); Assert.That(m.TotalXp, Is.EqualTo(2940)); Assert.That(m.EquippedCapstone, Is.Empty); }
    [Test] public void BranchRequiresBothMiddleNodesAndSpendIsAtomic() { var m = Introduced(); m.AddXp(1000); Assert.That(m.Purchase("B2"), Is.False); Assert.That(m.Purchase("B1"), Is.True); Assert.That(m.Purchase("B2"), Is.True); Assert.That(m.Purchase("B4"), Is.False); int before = m.UnspentPoints; Assert.That(m.Purchase("B2"), Is.False); Assert.That(m.UnspentPoints, Is.EqualTo(before)); Assert.That(m.Purchase("B3"), Is.True); Assert.That(m.Purchase("B4"), Is.True); }
    [Test] public void MigrationUsesProvenStarsAndCannotRepeat() { var m = new NineLivesModel(); var saved = new Dictionary<string,int> { { "intro", 3 }, { "two", 1 }, { "three", 3 }, { "unlocked", 0 } }; m.Migrate("intro", saved); Assert.That(m.TotalXp, Is.EqualTo(240)); Assert.That(m.LifetimePoints, Is.EqualTo(2)); m.Migrate("intro", saved); Assert.That(m.TotalXp, Is.EqualTo(240)); m.CompleteLevel("two", "intro", 1); Assert.That(m.TotalXp, Is.EqualTo(270)); }
    [Test] public void RoundTripKeepsPurchasedBuildAndSingleSelectedCapstone() { var m = Introduced(); m.AddXp(10290); foreach (var n in NineLivesCatalog.Nodes) Assert.That(m.Purchase(n.Id), Is.True); Assert.That(m.EquipCapstone("C5"), Is.True); Assert.That(m.EquipCapstone("C4"), Is.False); var loaded = JsonConvert.DeserializeObject<NineLivesModel>(JsonConvert.SerializeObject(m)); loaded.Normalize(); Assert.That(loaded.EquippedCapstone, Is.EqualTo("C5")); Assert.That(loaded.UnspentPoints, Is.Zero); Assert.That(loaded.Has("A5"), Is.True); }
    [Test] public void NormalizeDropsImpossiblePurchasesAndInvalidValues() { var m = new NineLivesModel { IntroGranted = true, TotalXp = -1, PurchasedMask = 32767, StarterPowerup = 99, EquippedCapstone = "A5", CreditedStars = null }; m.Normalize(); Assert.That(m.TotalXp, Is.Zero); Assert.That(m.PurchasedMask, Is.EqualTo(1)); Assert.That(m.StarterPowerup, Is.Zero); Assert.That(m.EquippedCapstone, Is.Empty); Assert.That(m.CreditedStars, Is.Not.Null); }
    [Test] public void NoProgressBeforeIntroOrFromNegativeXp() { var m = new NineLivesModel(); m.AddXp(1000); Assert.That(m.CompleteLevel("other", "intro", 3), Is.False); Assert.That(m.LifetimePoints, Is.Zero); m.CompleteLevel("intro", "intro", 0); m.AddXp(-100); Assert.That(m.TotalXp, Is.Zero); }
    [Test] public void ZeroStarClearCannotRepeatFirstClearBonusAfterRoundTrip() { var m = Introduced(); m.CompleteLevel("two", "intro", 0); Assert.That(m.TotalXp, Is.EqualTo(90)); m = JsonConvert.DeserializeObject<NineLivesModel>(JsonConvert.SerializeObject(m)); m.Normalize(); m.CompleteLevel("two", "intro", 0); Assert.That(m.TotalXp, Is.EqualTo(120)); m.CompleteLevel("two", "intro", 1); Assert.That(m.TotalXp, Is.EqualTo(155)); }
    [Test] public void EightPointThresholdIs2940AndFullTreeCosts10290() { var m = Introduced(); m.AddXp(2939); Assert.That(m.LifetimePoints, Is.EqualTo(7)); m.AddXp(1); Assert.That(m.LifetimePoints, Is.EqualTo(8)); m.AddXp(7349); Assert.That(m.LifetimePoints, Is.EqualTo(14)); m.AddXp(1); Assert.That(m.LifetimePoints, Is.EqualTo(15)); }
    [Test] public void UnknownNodeAndHighMaskBitsCannotAffectCurrency() { var m = Introduced(); Assert.That(m.Purchase("Z1"), Is.False); Assert.That(m.Has(null), Is.False); m.PurchasedMask = 1 << 25; m.Normalize(); Assert.That(m.PurchasedMask, Is.Zero); Assert.That(m.UnspentPoints, Is.EqualTo(1)); }
}
